name: 'Proofreader'
description: 'Automated docs editor. Robotic grammar enthusiast.'
inputs:
  path:
    description: 'File or glob pattern to proofread'
    required: false
    default: '{,!(node_modules)/**/}*.md'
  gh-token:
    description: 'Github API token'
    required: true
runs:
  using: 'node12'
  main: 'src/index.js'
branding:
  icon: 'edit-2'
  color: 'white'
